### ISSUE TITLE
[bug]:  Freepbx 17 Install Script Broken

### ISSUE THREAD

**Issue by koreybray** [FreePBX/issue-tracker#914]
### FreePBX Version

FreePBX 17

### Issue Description

Using install instructions on website for the manual install of Debian 12, and the Freepbx 17 install script now fails on fresh installs. 

Install does not complete.   Reinstall results in the same result. 

### Operating Environment

Full install log:
[freepbx17-install-2025.11.13-20.28.10.log](https://github.com/user-attachments/files/23538520/freepbx17-install-2025.11.13-20.28.10.log)

### Relevant log output

```shell
2025-11-13 20:48:27 - Reloading and restarting FreePBX 17
Reload Started

In Reload.class.php line 859:

Unable to connect to Asterisk Manager

reload [–json] [–dry-run] [–skip-registry-checks] [–dont-reload-asterisk]

2025-11-13 20:48:29 - ****** INSTALLATION FAILED *****
2025-11-13 20:48:29 - Error at line: 1310 exiting with code 1 (last command was: fwconsole reload >> “$log”)
2025-11-13 20:48:29 - Exiting script
```

**Comment by kapilgupta01** [comment]
Hi @koreybray it looks like asterisk is not running, can you manually try to check asterisk process 
In Reload.class.php line 859:
Unable to connect to Asterisk Manager

**Comment by koreybray** [comment]
@kguptasangoma This may be deeper than my current skill set... what exactly am I looking for here/where?  Happy to get the info.. but may need a little guidance.

**Comment by kapilgupta01** [comment]
1. ssh to your linux machine
2. run below command - 
`asterisk -rv"   -> check if you are able to connect to the asterisk shell 

3. if yes then try to run `fwconsole reload -v` again and check if this is working fine or not.
thanks

**Comment by koreybray** [comment]
When I run asterisk -rv: 

"Unable to connect to remote asterisk (does /var/run/asterisk/asterisk.ctl exist?)"

**Comment by kapilgupta01** [comment]
execute `fwconsole restart` and then run `fwconsole reload`

thanks

**Comment by koreybray** [comment]
@kguptasangoma  Done both of these...    no change. 


Here are the details:

fwconsole restart:

Asterisk not currently running
Running FreePBX shutdown...

Running Asterisk pre from Cdrpro module
Asterisk is not connected
Running Asterisk pre from Core module
Stopping Call Transfer Monitoring Service
Stopping Core FastAGI Server
Stopped FastAGI Server
Running Asterisk pre from Restapps module
RestApps Server is not running
Running Asterisk pre from Sangomaconnect module
SangomaConnect Server is not running
Running Asterisk pre from Sangomartapi module
Stopping Sangoma RT API Server...
Stopped Sangoma RT API Server
Running Asterisk pre from Scribe module
Stopping Scribe Service
Scribe was not running
Running Asterisk pre from Ucp module
Stopping UCP Node Server
[->--------------------------] 1 sec
Stopped UCP Node Server

Advanced Recovery service is not running
Queue Callback Server is not running
Queue Callback Event Server is not running
Asterisk already running
Running FreePBX startup...
Unable to run Pre-Asterisk hooks, because Asterisk is already running on PID 462745 and has been running for 0 seconds
Running Asterisk post from Adv_recovery module
Advanced Recovery is not licensed.
Running Asterisk post from Cdrpro module
Asterisk is not connected
Running Asterisk post from Core module
Starting Call Transfer Monitoring Service
Starting Core FastAGI Server...
[->--------------------------] 1 sec
Started Core FastAGI Server. PID is 463113
Running Asterisk post from Pagingpro module
Running Asterisk post from Restapps module
RestApps is not licensed.
Running Asterisk post from Sangomaconnect module
This product is not licensed
Running Asterisk post from Sangomartapi module
Starting Sangoma RT API Server...
[->--------------------------] 1 sec
Started Sangoma RT API Server. PID is 463316
Running Asterisk post from Scribe module
Scribe does not have license.
Running Asterisk post from Ucp module
Starting UCP Node Server...
[->--------------------------] 1 sec
Started UCP Node Server. PID is 463577
Running Asterisk post from Vqplus module
Queues Pro is not licensed.



 fwconsole reload:


Reload Started

In Reload.class.php line 859:

  Unable to connect to Asterisk Manager


reload [--json] [--dry-run] [--skip-registry-checks] [--dont-reload-asterisk]

**Comment by koreybray** [comment]
Just an update... on the same system i tried installing the FREEPBX 17 ISO, and it gets stuck on a loop of the install, failing and rebooting and trying to install freepbx 17 again.    Something may have changed with asterisk or something else that the current install scripts are not configured to handle correctly perhaps?

**Comment by kapilgupta01** [comment]
Hi @koreybray is that getting stuck on same `Unable to connect to Asterisk Manager` error ?

**Comment by koreybray** [comment]
@kguptasangoma  correct.

**Comment by kapilgupta01** [comment]
Hey @koreybray 

Is it possible to send me email to kgupta@sangoma.com with your system ssh details so I can ssh to check the issue?

I hope your system is without any configuration so no obligation for me to ssh to your system.

Thanks
Kapil

**Comment by chrsmj** [comment]
What are the server specs in use? CPU? RAM? Disk size? Hosted or bare metal?

**Comment by koreybray** [comment]
> [kgupta@sangoma.com](mailto:kgupta@sangoma.com)

Hi Kapil,

Emailed you with the details.   Firewall opened for you now... please use the port on the 2nd email (sorry mistyped)

**Comment by koreybray** [comment]
> What are the server specs in use? CPU? RAM? Disk size? Hosted or bare metal?

Hi @chrsmj It's an older system, used for Freepbx 15, that was upgraded.   It ran and installed Freepbx 17 before (months ago) before a misconfig trashed the system and went to do a fresh install.   This time the install script fails.

It's a homebuilt server in house.  It's an older, but should and has powered our use case very well.

2 x 256G ssd drives (software raid1)
4g RAM
Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz

**Comment by kapilgupta01** [comment]
Hi @koreybray I am not able to ssh to your system to debug this issue, replied to your email as well. 

Still waiting for the access to check this issue.

thanks

**Comment by koreybray** [comment]
@kguptasangoma   just emailed you now.    Let me know if you got it.. I never got anything recently from you.   Hopefully it's not caught in a spam folder

**Comment by koreybray** [comment]
Hi @kguptasangoma,

I'm around tonight.   Let me know if you received the email from today.   If not or if the login info doesn't work for you I may send you an IP based url instead.   I doubled checked today and the root login I sent does work remotely for me.

Let me know!

Korey

**Comment by ramarajan222** [comment]
Hi @koreybray We checked your system and found that Asterisk was crashing while loading res_digium_phone.so. To bring Asterisk back up, we added noload = res_digium_phone.so in modules.conf.

This issue occurs only with the latest asterisk22-res-digium-phone (3.6.11) package. If you need to use Sangoma D & P phones, please install the earlier stable version of DPMA using the command below:

`apt install asterisk22-res-digium-phone=3.6.9-1.sng12`

I also raised an internal Jira ticket for further investigation of this issue.

**Comment by koreybray** [comment]
@ramarajan222  Thanks so much for looking at this.   I'm guessing this also would lead to the freepbx GUI site not installing correctly?     Even after your install, the GUI is down.. but the Apache2 Debian Default Page shows on port 80.  This is the same as my attempts.   

I don't use digium currently... is there an install option to not install digium using the install script currently?   Was looking at the list and didn't see that option.

**Comment by koreybray** [comment]
@ramarajan222 UPDATE: I ran the install script with the "--noasterisk" argument and the web GUI is now up and operational..   I didn't want to mess up what you did but took the risk..

Regarding the digium issue you opened a ticket for, will a notification be given once/if this is corrected?   AND/OR is there an argument that can be applied to avoid installing this defective digium package?   Appreciate everything you guys have done here!  Hopefully access helped get you to the bottom of this.

**Comment by ramarajan222** [comment]
Hi @koreybray 

This issue has been fixed in the new DPMA version (3.6.12). I have already installed this fixed version on your system and confirmed that it is working fine.

```
dpkg -l | grep digium
ii  asterisk22-res-digium-phone                      3.6.12-1.sng12                            amd64        Provides a number of enhanced provisioning and application capabilities for Digium SIP phones

```
Note: Currently, this version is in the testing repo and it will be pushed to the PROD repo in a week or two.

**Comment by stealthylabs** [comment]
@ramarajan222  I am still seeing the same issue and the latest install script keeps installing the 3.6.11 digium-phone module. Same as in issue linked above: https://github.com/FreePBX/sng_freepbx_debian_install/issues/215 

i have a newly setup Debian 12 server and the Git script actually does **not** work, so requesting a better fix.

**Comment by stealthylabs** [comment]
Alright. For those who land on this page. I ran the script, then it failed. i then set the `noload = res_digium_phone.so` in `/etc/asterisk/modules.conf` and then re-ran the script and set `--noasterisk` `--skipversion` as the commandline options.

once everything finishes, you can then check the site on `http://<IP ADDRESS>/index.php` to get to the admin screen.

**Comment by koreybray** [comment]
Hi @stealthylabs ..  that was the workaround they came up with but it's disappointing it hasn't yet being applied as a full fix so the script installs without hoop jumping.    @ramarajan222 @kguptasangoma  perhaps can provide an update on where that stands.

**Comment by ramarajan222** [comment]
Hi @koreybray @stealthylabs  The latest digium-phone module (3.6.12) is now available in the prod repo. Please give it another try. thanks.

**Comment by digdug3** [comment]
Just tested with Debian Bookworm v12.13 same issue still

**Comment by digdug3** [comment]
Retried today, 04 feb. 2026, with Bookworm v12.13 and it works. Looks like there was some kind of hickup?
Thanks!
